name: 'Build and push docker to ghcr and ecr'

env:
  DOCKERFILE: ./docker/docker-cuda/DockerfileCombined
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: verticalstudio-ai/llamafactory/fine-tune:${{github.ref_name}}

on:
  release:
    types:
      - created
      - released
      - published

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
